server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workbookDb
    username: test_user
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google-sheets:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth/redirect/google-sheets"
            scope: https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
        provider:
          google-sheets:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline
            token-uri: https://oauth2.googleapis.com/token

jwt:
  audience: ${GOOGLE_OAUTH_AUDIENCES:${GOOGLE_OAUTH_CLIENT_ID}}

logging:
  level:
    org:
      springframework:
        security: TRACE