server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workbookDb
    username: test_user
    password: test_pwd
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google-sheets:
            client-id: 1048130131806-7hv8b0pnlobhlmpk5mj30jfui2nmei76.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth/redirect/google-sheets"
            scope: https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
        provider:
          google-sheets:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline
            token-uri: https://oauth2.googleapis.com/token

jwt:
  audience:
    - 1048130131806-7hv8b0pnlobhlmpk5mj30jfui2nmei76.apps.googleusercontent.com
    - 1048130131806-f0pbb31sj8cduou6b9jldnmqspl2sabd.apps.googleusercontent.com
    - 407408718192.apps.googleusercontent.com # demo purpose need to be removed

logging:
  level:
    org:
      springframework:
        security: TRACE